server:
  port: 20003
spring:
  application:
    name: @artifactId@
  #数据源配置
  datasource:
    url: ${mate.datasource.url}
    username: ${mate.datasource.username}
    password: ${mate.datasource.password}
