server:
  port: 20001
spring:
  application:
    name: @artifactId@
#数据源配置
  datasource:
    url: ${mate.datasource.url}
    username: ${mate.datasource.username}
    password: ${mate.datasource.password}

dubbo:
  registry:
    #   The Spring Cloud Dubbo's registry extension
    ##  the default value of dubbo-provider-services is "*", that means to subscribe all providers,
    ##  thus it's optimized if subscriber specifies the required providers.
    address: spring-cloud://localhost
#    address: nacos://127.0.0.1:8848
  #   The traditional Dubbo's registry also is supported
  #   address: zookeeper://127.0.0.1:2181
  cloud:
    # The subscribed services in consumer side
    subscribed-services: ${provider.application.name}

  consumer:
    check: false

provider:
  application:
    name: mate-admin